/*
 MIT License {@link http://creativecommons.org/licenses/MIT/}
 MIT License {@link http://creativecommons.org/licenses/MIT/}
got from http://balupton.github.com/jquery-history/demo/, modified to support jQuery 1.9
 */
"undefined"===typeof window.console&&(window.console={});
"undefined"===typeof window.console.emulated&&("function"===typeof window.console.log?window.console.hasLog=!0:("undefined"===typeof window.console.log&&(window.console.log=function(){}),window.console.hasLog=!1),"function"===typeof window.console.debug?window.console.hasDebug=!0:("undefined"===typeof window.console.debug&&(window.console.debug=!window.console.hasLog?function(){}:function(){for(var b=["console.debug:"],a=0;a<arguments.length;a++)b.push(arguments[a]);window.console.log.apply(window.console,
    b)}),window.console.hasDebug=!1),"function"===typeof window.console.warn?window.console.hasWarn=!0:("undefined"===typeof window.console.warn&&(window.console.warn=!window.console.hasLog?function(){}:function(){for(var b=["console.warn:"],a=0;a<arguments.length;a++)b.push(arguments[a]);window.console.log.apply(window.console,b)}),window.console.hasWarn=!1),"function"===typeof window.console.error?window.console.hasError=!0:("undefined"===typeof window.console.error&&(window.console.error=function(){var b=
    "An error has occured.";if(window.console.hasLog){for(var b=["console.error:"],a=0;a<arguments.length;a++)b.push(arguments[a]);window.console.log.apply(window.console,b);b="An error has occured. More information is available in your browser's javascript console."}for(a=0;a<arguments.length&&"string"===typeof arguments[a];++a)b+="\n"+arguments[a];if("undefined"!==typeof Error)throw Error(b);throw b;}),window.console.hasError=!1),"function"===typeof window.console.trace?window.console.hasTrace=!0:("undefined"===
    typeof window.console.trace&&(window.console.trace=function(){window.console.error("console.trace does not exist")}),window.console.hasTrace=!1),window.console.emulated=!0);
(function(b){b.History?window.console.warn("$.History has already been defined..."):(b.History={options:{debug:!1},state:"",$window:null,$iframe:null,handlers:{generic:[],specific:{}},extractHash:function(a){return a.replace(/^[^#]*#/,"").replace(/^#+|#+$/,"")},getState:function(){return b.History.state},setState:function(a){var c=b.History;a=c.extractHash(a);c.state=a;return c.state},getHash:function(){return b.History.extractHash(window.location.hash||location.hash)},setHash:function(a){a=b.History.extractHash(a);
  "undefined"!==typeof window.location.hash?window.location.hash!==a&&(window.location.hash=a):location.hash!==a&&(location.hash=a);return a},go:function(a){var c=b.History;a=c.extractHash(a);var d=c.getHash(),f=c.getState();a!==d?c.setHash(a):(a!==f&&c.setState(a),c.trigger());return!0},hashchange:function(){var a=b.History,c=a.getHash();a.go(c);return!0},bind:function(a,c){var d=b.History;c?("undefined"===typeof d.handlers.specific[a]&&(d.handlers.specific[a]=[]),d.handlers.specific[a].push(c)):d.handlers.generic.push(a);
  return!0},trigger:function(a){var c=b.History;"undefined"===typeof a&&(a=c.getState());var d,f,g,e;if("undefined"!==typeof c.handlers.specific[a]){e=c.handlers.specific[a];d=0;for(f=e.length;d<f;++d)g=e[d],g(a)}e=c.handlers.generic;d=0;for(f=e.length;d<f;++d)g=e[d],g(a);return!0},construct:function(){var a=b.History;b(document).ready(function(){a.domReady()});return!0},configure:function(a){var c=b.History;c.options=b.extend(c.options,a);return!0},domReadied:!1,domReady:function(){var a=b.History;
  if(!a.domRedied)return a.domRedied=!0,a.$window=b(window),a.$window.bind("hashchange",this.hashchange),setTimeout(a.hashchangeLoader,200),!0},nativeSupport:function(){return!0},hashchangeLoader:function(){var a=b.History;if(a.nativeSupport())a.getHash()&&a.$window.trigger("hashchange");else{var c;if(b.browser.msie){a.$iframe=b('<iframe id="jquery-history-iframe" style="display: none;"></iframe>').prependTo(document.body)[0];a.$iframe.contentWindow.document.open();a.$iframe.contentWindow.document.close();
  var d=!1;c=function(){var b=a.getHash(),c=a.getState(),e=a.extractHash(a.$iframe.contentWindow.document.location.hash);c!==b?(d||(a.$iframe.contentWindow.document.open(),a.$iframe.contentWindow.document.close(),a.$iframe.contentWindow.document.location.hash=b),d=!1,a.$window.trigger("hashchange")):c!==e&&(d=!0,a.setHash(e))}}else c=function(){var b=a.getHash();a.getState()!==b&&a.$window.trigger("hashchange")};setInterval(c,200)}return!0}},b.History.construct())})(jQuery);
